<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-465</name>
   <tag></tag>
   <elementGuidId>8f0b6f2f-1dac-4325-83c3-6502dc0b57fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-465</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-465']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0ada0e1-ddd0-4e0c-954f-1fc683579bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-465</value>
      <webElementGuid>d456d347-77da-45a9-bbf9-b4fe83372590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8d00d31-5ec1-4f98-841e-cc2bfdd625cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-465&quot;)</value>
      <webElementGuid>8e056cb5-9dfa-4508-b675-7dd78d528ce6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-465']</value>
      <webElementGuid>00ed8df7-7e39-40db-b0f4-8bdcab539a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[3]/div/div/div/input</value>
      <webElementGuid>a978d877-a1e9-49b3-b664-01c346eb4601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>f53a43e7-be69-4a0a-af4a-41c66792fbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-465' and @type = 'text']</value>
      <webElementGuid>b0b6dd9c-9505-4d64-802f-ed41cd474100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
