<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-462</name>
   <tag></tag>
   <elementGuidId>14a91845-c371-447e-9f07-77a39f8ea022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-462</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-462']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>652b8829-f8c7-4f66-8425-bcc458906cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-462</value>
      <webElementGuid>101ecd6e-ea44-449b-816f-a05788bd88d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b119ef86-b4cf-4182-b06b-0470c4feeb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-462&quot;)</value>
      <webElementGuid>53dae0ae-dfaa-4747-9641-4f732fa3a326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-462']</value>
      <webElementGuid>3a442b8d-4197-4626-ba40-b32c0cd9f2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>ef00bc23-766a-421b-8fb0-0d9e22975952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>a2158560-2de3-464f-b360-1d0119a3d036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-462' and @type = 'text']</value>
      <webElementGuid>c3c4e12c-6392-44e3-a3e2-89a80396dd00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
