<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full name_input-459</name>
   <tag></tag>
   <elementGuidId>8056e76b-1929-49a2-95ca-30eb22c72f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-459</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-459']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05fe33c9-c09a-4ae6-b6f5-839361b9a4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-459</value>
      <webElementGuid>22774e3d-5e07-4b28-a107-6b8329e50812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16a71d52-a3c9-47cf-8a86-c1287f213070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-459&quot;)</value>
      <webElementGuid>ef9d633a-eb53-452c-9ef8-3f01ff06d446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-459']</value>
      <webElementGuid>2fc29bd9-5616-4d62-af46-8f1b23b97d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>63e9a33b-9543-42ff-b420-c689f09a47d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4747bf02-a43b-45fb-8db8-1dc2297dbce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-459' and @type = 'text']</value>
      <webElementGuid>1db8672e-fc9b-48d9-84b5-65f3f83aca89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
