<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1118</name>
   <tag></tag>
   <elementGuidId>8374e8ef-ce0d-468c-9721-7bc6e6655275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1118</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1118']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb55effe-0a11-4168-a888-10f9b2c6139b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1118</value>
      <webElementGuid>df116f07-b0b3-4951-aad8-6d8db42d7d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9ec8a84-69dc-4585-b99d-fb7503258621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1118&quot;)</value>
      <webElementGuid>e0c7c31e-d1cc-4513-ad99-5e0b7b969007</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1118']</value>
      <webElementGuid>b7ecd0c4-e889-4568-aca8-38bcf45d299f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>9de31c9b-e97a-4c68-b79d-1a06b56a32c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>b57f6181-2b00-4571-a65f-8c207e0f3af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1118' and @type = 'text']</value>
      <webElementGuid>582713bc-38ff-48ac-a61f-080a5765d6e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
