<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1115</name>
   <tag></tag>
   <elementGuidId>93e987c7-c4c0-4d13-8c96-a20a7432e555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1115</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1115']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c507835-c067-4cf9-befb-8b4f36262065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1115</value>
      <webElementGuid>66623931-0d5d-4b41-9295-0dad9e1e8dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d634e030-c3c7-4aac-905c-f0d8363e5e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1115&quot;)</value>
      <webElementGuid>a55b02aa-4922-420a-a309-6b421a99f841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1115']</value>
      <webElementGuid>c8f8f037-c4fb-4a15-91e9-d69fce6f7054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>5457681b-c833-482b-8c87-8bf4e257e7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fb4235b1-c469-4c2b-bc59-260960ae8929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1115' and @type = 'text']</value>
      <webElementGuid>aeb8ac59-eef4-4ba1-8095-70af451a6181</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
