<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1013</name>
   <tag></tag>
   <elementGuidId>e446c19c-e91e-41f1-9b00-574158bad5b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1013</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1013']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53c07a83-093d-4931-80c6-fb65f6e2d5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1013</value>
      <webElementGuid>9625c2e2-d7f4-4395-b31a-38d13b99d82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc16a395-4ccc-4f06-b1ef-3455a3f85492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1013&quot;)</value>
      <webElementGuid>8ccd95ac-cabf-4c1f-80a8-7f21e65aa97e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1013']</value>
      <webElementGuid>725a3e38-5bd3-412d-8a49-c77d8263fd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>7580f6bc-0d79-4723-9407-c17b360f50eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>8a2bf667-4d25-4a0a-a57e-3e3c8611f0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1013' and @type = 'text']</value>
      <webElementGuid>5f8006f6-0388-48ad-87f9-53ecfac12c6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
