<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1148</name>
   <tag></tag>
   <elementGuidId>0ca00f53-8195-44b0-813d-dd08c7f0f669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1148</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1148']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f39f13fd-28c3-474b-9a9c-a7cd0d78e7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1148</value>
      <webElementGuid>1bdbea0c-3658-46f9-a03f-4494c7ae26af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1edc8c5-f0b1-49ed-af9f-75c0a50c726d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1148&quot;)</value>
      <webElementGuid>17e13908-1468-4205-add4-53b0319cbcd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1148']</value>
      <webElementGuid>6e899a38-4e14-4fed-8ce3-fbacac5b77c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>70511a24-e0fc-4b8a-9368-40ef9d450338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>f56edc3e-677e-469c-b69b-c15d1b1bb51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1148' and @type = 'text']</value>
      <webElementGuid>e59d8360-7c3c-44b2-93a1-ed51506e6291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
