<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1145</name>
   <tag></tag>
   <elementGuidId>8b7fae90-1273-418d-9598-c818128cf50a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1145</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1145']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a733c28c-2a6c-4bd8-9848-8b4414a5f098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1145</value>
      <webElementGuid>d31b7df1-995a-4d2b-9b87-a9497014397b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00afdbc9-045b-4aee-9203-add08d8e8bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1145&quot;)</value>
      <webElementGuid>3a6ee1de-517c-420f-9e77-05e13f17b876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1145']</value>
      <webElementGuid>b3795ec7-4500-4d69-90f3-484720a7f643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>60b95adc-d02c-479e-b663-5b4d42cb4b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f8eca2e2-314b-41ef-b89e-cd0065dc9e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1145' and @type = 'text']</value>
      <webElementGuid>c89d7b3f-ea10-4695-b91b-9f86b9256667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
