<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1013</name>
   <tag></tag>
   <elementGuidId>43505f91-7436-4715-baed-e102e842b4e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1013</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1013']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b14b990a-b23d-4a68-9470-1458b0526b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1013</value>
      <webElementGuid>d8a532c9-7cf3-4208-9268-a5080e8f5c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5f74e6a-625b-4dd5-8ccb-595046bb251c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1013&quot;)</value>
      <webElementGuid>8d8706a7-7a38-4c35-90b3-65c46f441eca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1013']</value>
      <webElementGuid>ba41510a-3678-44fb-a7d8-b914c44c4812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>0a6b214c-f70b-49ea-9b3d-83b305b56ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>36027f69-30fb-4681-8467-e0677757b9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1013' and @type = 'text']</value>
      <webElementGuid>0601661e-ce30-4855-9ab6-ae88f28e1c56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
