<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1010</name>
   <tag></tag>
   <elementGuidId>b7de0205-24e7-4b44-a6b0-8a5d4efa6118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1010</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1010']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80a02bdc-54bf-4a83-904f-9aeb8de43292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1010</value>
      <webElementGuid>ca0d81ec-c347-484a-ba0d-3f6b989ca5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c2e6b73-4679-47be-8e3d-e5e07e9df6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1010&quot;)</value>
      <webElementGuid>34f7eb97-9fbe-46a2-a782-80cad52ab2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1010']</value>
      <webElementGuid>8150376a-8c85-4dc7-969e-0ab2ac5132a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>743f54f4-86df-4b2f-8384-d8d6dfb9aa1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1ff0c3d2-e407-4a21-97b9-5a4346dbb13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1010' and @type = 'text']</value>
      <webElementGuid>bddcc185-2275-4bb5-84ca-52001ef8b76d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
