<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sony PS5Rp 299-1Total Qty1Total Bayar299 Bayar</name>
   <tag></tag>
   <elementGuidId>2fd8de10-640b-4ecf-96ea-4d0ec8f1f02b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>421112f3-466b-4d04-97ce-16f4d0cae3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>fd08f585-cc2d-4215-ad43-47410f0cfcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sony PS5Rp 299-1+Total Qty1Total Bayar299 Bayar </value>
      <webElementGuid>7856454d-effe-479d-a5d6-76015a347880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]</value>
      <webElementGuid>d87fc592-2be8-43d1-88f4-799d5eff69c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div</value>
      <webElementGuid>4518a93e-6c25-4c09-b72f-3dc4bf5cd208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::div[4]</value>
      <webElementGuid>e80c8fc4-6c7d-416f-85e8-bb6a46a7d1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div</value>
      <webElementGuid>f7f7b6f6-5bff-4945-a309-8e225fef8299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sony PS5Rp 299-1+Total Qty1Total Bayar299 Bayar ' or . = 'Sony PS5Rp 299-1+Total Qty1Total Bayar299 Bayar ')]</value>
      <webElementGuid>c15c2bf7-35b0-402a-926d-61d73e5b10d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
