<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-929</name>
   <tag></tag>
   <elementGuidId>194478d8-6b4e-4f83-a1eb-760a83e8b507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-929</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-929']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6e11b7f-47bb-4be7-989e-26eeba5c7305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-929</value>
      <webElementGuid>50fb003a-ab67-4058-a27d-4fe7aba1cea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0de57d7-470b-426b-af92-b58d5a227aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-929&quot;)</value>
      <webElementGuid>ecb8c366-643c-4bd9-89a5-b2e43c336d32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-929']</value>
      <webElementGuid>2fdbe541-53d1-457b-a7ca-72bf315179b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>b956d4b7-990e-485d-b559-50c1b122e842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>370c4556-2cdc-4be3-a00f-4e8327bbc52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-929' and @type = 'text']</value>
      <webElementGuid>2f217320-e3db-423b-ba21-2f7e4e0ad7b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
