<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-932</name>
   <tag></tag>
   <elementGuidId>54f46b99-395e-4c31-b8c3-e27076ab616b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-932</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-932']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>841a9eed-4417-4b2a-87c5-332d3214ad04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-932</value>
      <webElementGuid>98371c1e-9341-4ca8-89cd-f7bde028f60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>578b5442-47d5-4d7a-8e04-4736201fca4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-932&quot;)</value>
      <webElementGuid>b80b7df0-ed04-433c-8bf1-b369f253f834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-932']</value>
      <webElementGuid>ce888bf4-9069-419b-9af7-2f492dc5d051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>c53485b6-9dfa-4c0f-a3a6-2e09e61ac31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>4bb22e33-9506-4868-a92a-6e866613160f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-932' and @type = 'text']</value>
      <webElementGuid>304279d4-efc5-404b-8597-ec1142e1cefb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
