<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bayar</name>
   <tag></tag>
   <elementGuidId>abdf771b-8169-481d-a669-83ddd9e230ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-bayar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-bayar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45cbe7c5-7304-4486-b931-0c91b453846d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbc0a0c4-e471-4e19-a6fe-8cbd769d4399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--large primary</value>
      <webElementGuid>518ef395-c938-4bfc-9c7b-feeab8d0a6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-bayar</value>
      <webElementGuid>4ad66b3f-cc9a-4eea-bbb5-f1551d9444cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Bayar </value>
      <webElementGuid>6cbccfd9-2a73-4bb7-9afd-1287b4bba44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-bayar&quot;)</value>
      <webElementGuid>59f4d102-3276-4f23-bebb-2456add05190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-bayar']</value>
      <webElementGuid>b3d3bbce-e07f-4357-a06a-e056774b47dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/button</value>
      <webElementGuid>0fef6ad2-0844-4c5f-a48a-26f72abac97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Bayar'])[1]/following::button[1]</value>
      <webElementGuid>48c530f4-5898-4e94-94ae-8a9f467ed63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Qty'])[1]/following::button[1]</value>
      <webElementGuid>bd7a5b45-7577-4017-b6e8-a7ccc071905a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'button-bayar', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>a28f9661-96c0-43c5-9512-7a04aa4b5ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>e6a2b2d1-c828-42f9-9f16-9be4c5397e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'button-bayar' and (text() = ' Bayar ' or . = ' Bayar ')]</value>
      <webElementGuid>292cf6f3-1334-497b-ab4d-f75ddb46b7fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
