<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1118</name>
   <tag></tag>
   <elementGuidId>6086f495-e5db-4aa6-b64a-a0c1b5915fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1118</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1118']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43e94b0f-c37c-4d08-a1b8-e455c35915e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1118</value>
      <webElementGuid>3b33cd36-5e7c-4014-abcf-2a109f986619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ee05f77-e8f4-4d26-ae3d-d3e85200113d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1118&quot;)</value>
      <webElementGuid>7247c6d6-8e97-4bca-a067-ff75d5ee8810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1118']</value>
      <webElementGuid>ec29a8f1-6497-48f6-ab21-246d8fdf1ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>099e837e-2a0a-46d6-847b-5e5ccfa70b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>4b16bab8-ef31-44bd-b46b-2bda29e1df91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1118' and @type = 'text']</value>
      <webElementGuid>627cd440-e9f7-4548-bd93-dc2319a5e85f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
