<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1115</name>
   <tag></tag>
   <elementGuidId>e4c5c5f7-2090-469a-9828-48dce3d1e314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1115</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1115']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8c53796-5fff-4866-bd26-47b26ecd0fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1115</value>
      <webElementGuid>0fe1ead1-e961-435d-986e-f0e0f84e0cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f1592e7-7f3e-41e0-974d-2179cec35078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1115&quot;)</value>
      <webElementGuid>7c7f091a-201b-4334-bbf8-c4beb6522c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1115']</value>
      <webElementGuid>382df06b-ca08-437d-bcba-2ff7ca2e43d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>491359aa-0ee8-4949-b0bd-972fbe0a7ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>05d5e22b-684e-4651-89ce-662d0fb74bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1115' and @type = 'text']</value>
      <webElementGuid>41d43ae7-f505-4231-8368-cb0e61e27192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
