<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1010</name>
   <tag></tag>
   <elementGuidId>274978bc-bf89-476f-b7dc-b70b4a9dadf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1010</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1010']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b98eeae1-b187-4098-8c49-85b5b27539a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1010</value>
      <webElementGuid>b82fd10d-1f1c-4f18-accd-f315e134568a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bb1d9dd-034d-4171-9e33-fd61b51ee510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1010&quot;)</value>
      <webElementGuid>d02d458f-2631-4be0-9d66-f71c81a256d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1010']</value>
      <webElementGuid>fbcddfb3-974f-43a0-a14e-7be4e78e7e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>1026e16a-1b7d-4123-968c-b2435666b14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b6c141c2-29b2-4888-bf5a-a90b55bc814b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1010' and @type = 'text']</value>
      <webElementGuid>2ff4990a-1b34-45e9-9084-1c5b774d9d7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
