<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-1</name>
   <tag></tag>
   <elementGuidId>a0882d8d-3e4c-485a-8f37-2ac05c7e90d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order-204']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order-204 > div.v-list-item__icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1549dbbe-c013-48e9-8f71-9023d62366c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__icon</value>
      <webElementGuid>85fefcef-523d-41a2-9549-34b4d4398755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-1+</value>
      <webElementGuid>7420104e-9cd3-4e2d-9cc9-54f96f5298a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-204&quot;)/div[@class=&quot;v-list-item__icon&quot;]</value>
      <webElementGuid>33a4c289-c5aa-400f-94da-23bd4eb211b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order-204']/div[2]</value>
      <webElementGuid>1e938bdd-7a16-4564-b268-3d76537d2ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atari Jaguar'])[1]/following::div[2]</value>
      <webElementGuid>1be78998-5cac-49cc-be53-b205f9c035a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>cb9c874a-116b-472c-9a37-ed16aeca1b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '-1+' or . = '-1+')]</value>
      <webElementGuid>288a557a-5e49-4c76-b82c-a4719fe60457</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
