<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sony PS5  play has no limits  4  Rp 299_cdc032</name>
   <tag></tag>
   <elementGuidId>4832d3fa-f80f-4f05-999f-24e2604bfd2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8f77428-26ea-42fa-8e15-ac9462522468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>2cce31aa-e9ee-4a53-9e82-744ccbf1cb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4 col-lg-3 col-6</value>
      <webElementGuid>ef758ffd-6304-4002-a64e-3ba02494e0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sony PS5  play has no limits   4  Rp 299DetailBeli</value>
      <webElementGuid>09d88ed1-b0d9-4482-a43f-33556d6e23bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;13&quot;)</value>
      <webElementGuid>9d3fde6c-b32c-4de7-a5ff-06a09a39f570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='13']</value>
      <webElementGuid>92de9b65-f935-4bb9-8dcc-593cc7330c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div</value>
      <webElementGuid>dc37e129-2ce8-4835-b842-93dfff7a85d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select category ...'])[1]/following::div[12]</value>
      <webElementGuid>dd81849c-edf1-4e32-a505-38355de989d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::div[20]</value>
      <webElementGuid>a9b6f80e-4cfd-4719-8227-6eb51dc89d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>7cb7a9b2-a8aa-4189-858b-2d58c473f302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '13' and (text() = ' Sony PS5  play has no limits   4  Rp 299DetailBeli' or . = ' Sony PS5  play has no limits   4  Rp 299DetailBeli')]</value>
      <webElementGuid>360f3cb1-849f-4713-beef-01367ff60b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
