<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1007</name>
   <tag></tag>
   <elementGuidId>ff31ad1d-542e-4dec-8cf2-546c13271b06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1007</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1007']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0c58337-e9bb-4c87-afcc-3449b3a36ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1007</value>
      <webElementGuid>74e04d97-fe81-4218-8b2b-c912ce596b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>446cf23b-b40e-4de1-81cf-811705026af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1007&quot;)</value>
      <webElementGuid>2742602a-0be8-44d2-8836-e3ae1f1f593d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1007']</value>
      <webElementGuid>cfa676df-0b33-4414-9a1a-a9b86cdaae65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>6413add5-c527-45f0-9b56-6368edab599c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>9d430768-9de6-49aa-b8ee-47cb2c29ab00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1007' and @type = 'text']</value>
      <webElementGuid>bd89662b-598b-40bd-b7bc-9ac6298fa01c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
