<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1004</name>
   <tag></tag>
   <elementGuidId>b9650de3-9631-4a6e-ab45-e03448f5b2d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1004</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1004']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86c0b7ee-e135-4e7d-88a8-0901fe36293a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1004</value>
      <webElementGuid>0427454f-caa1-418e-8559-23575f7e5550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa628447-ea70-4fec-aee4-676e0718bb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1004&quot;)</value>
      <webElementGuid>8727624f-542e-404d-922a-eb65c69d7e0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1004']</value>
      <webElementGuid>01a32ca1-b7b3-4a95-90f1-d9a6d877fbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>1475056a-6b9e-41ad-bd2a-92d2f1b7f3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>af2b07d6-a92b-492e-be24-a35aff16ed4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1004' and @type = 'text']</value>
      <webElementGuid>5aecd260-86c5-41f9-9126-739694ef101a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
