<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-875</name>
   <tag></tag>
   <elementGuidId>7ef79958-c12b-4b12-a672-f7f9b5213e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-875</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-875']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d76e95b-5190-41d4-bae0-dc4ad8dc67e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-875</value>
      <webElementGuid>eeac11d6-b466-44e2-9130-13b35af732fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5d1d90a-6d2f-488f-9830-1bd8d76b5e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-875&quot;)</value>
      <webElementGuid>0a15a4cd-5641-480d-be60-0df56c71bd4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-875']</value>
      <webElementGuid>0315d53e-7c62-4785-b150-b3540909b634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>bceb930f-2f08-4029-8b68-5ee43ae542eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b8af401b-a3f6-4b40-a560-9f1913b87cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-875' and @type = 'text']</value>
      <webElementGuid>31fac709-8bb9-4c2d-83da-b5596930a2b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
