<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-878</name>
   <tag></tag>
   <elementGuidId>feb39bd1-edb2-45db-b653-c0ebd6b7d6a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-878</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-878']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85b321f3-14ba-4122-b581-e52321d2c794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-878</value>
      <webElementGuid>ff90355d-45e4-4c85-a232-b1f1f69170a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49ac67d2-7781-4153-8043-0c390c2b5094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-878&quot;)</value>
      <webElementGuid>375c7ae7-4a75-478d-988c-3acf03253d0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-878']</value>
      <webElementGuid>2edece96-9aa3-46c0-8b20-2f24649cc699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>daca5db5-ade5-4bdf-aeb8-07f01aef4f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>ebfbb9c0-a5fa-4a6c-9867-be3a52cbb908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-878' and @type = 'text']</value>
      <webElementGuid>7f9898b6-e1b7-4ca1-af54-801db8254037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
