<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_play has no limits_v-icon notranslate fas_c5a26b</name>
   <tag></tag>
   <elementGuidId>e6de7a8c-2cb0-4278-a44b-f0c1f1c408d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.fas.fa-star.theme--light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='13']/div/div[3]/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>caa5aa20-781b-4e17-afba-ddee01522fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51100ca4-bc6c-4b3a-b649-f2ca9c571640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate fas fa-star theme--light</value>
      <webElementGuid>ef15ef76-8a46-4f79-aa58-d434c435edf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;13&quot;)/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__actions d-block&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/i[@class=&quot;v-icon notranslate fas fa-star theme--light&quot;]</value>
      <webElementGuid>e09bacf6-772c-4d5e-b903-42c3386dea53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='13']/div/div[3]/div/div/i</value>
      <webElementGuid>9a31bdbf-a9e5-4507-bcc7-8b2852939bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/i</value>
      <webElementGuid>4c2d8c36-16b6-498e-afea-8fa75238005a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
