<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1010</name>
   <tag></tag>
   <elementGuidId>9c1eeaee-a060-412a-a9a2-9b606ac367ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1010</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1010']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8de05d84-f951-4c32-8a05-8669e319d852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1010</value>
      <webElementGuid>6a553b7a-d20b-443a-9db9-44a744320372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7aaecabf-1d15-448b-8192-787345aa64c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1010&quot;)</value>
      <webElementGuid>a387fca9-bfa6-4879-bc57-9c0b8e5dfe99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1010']</value>
      <webElementGuid>91603bec-cc21-43b9-acf7-fd3c093cacbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>1657eec0-ffc3-444f-a911-432635b1d4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2778956d-19ae-41ec-be3f-b78f4b776d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1010' and @type = 'text']</value>
      <webElementGuid>55396aad-6908-4145-8d2e-c7ad7d49337a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
