<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-926</name>
   <tag></tag>
   <elementGuidId>e781cdbe-6d96-412e-a23a-f6ba137d3a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-926</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-926']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf5588bf-c9b0-4a25-9447-7623f1fd7984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-926</value>
      <webElementGuid>c4a277de-5bd2-4e9d-9ebd-655ce1a3a172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81614673-738a-4e3f-a3f8-d51801426f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-926&quot;)</value>
      <webElementGuid>724799a3-8684-447f-9b58-5c651c42a148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-926']</value>
      <webElementGuid>1bc39ccd-e785-445c-99a7-fd17f006eff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>b82fc044-c90e-4a73-8402-034e5d6fd05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>5b1b12aa-7d90-4e54-a39f-c3cb0fd82b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-926' and @type = 'text']</value>
      <webElementGuid>4f506e71-3f9b-4fb4-b45e-382fed150be4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
