<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-923</name>
   <tag></tag>
   <elementGuidId>c74c63f6-38e6-4cfa-89db-1268a3e43499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-923</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-923']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1f69c79-ce56-45ba-9496-5cd8fbc4b790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-923</value>
      <webElementGuid>a9cf8674-4e13-4a86-aad3-a34a2e3ac9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85e5162f-08ae-4cd2-a3cb-aee47b629692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-923&quot;)</value>
      <webElementGuid>ab13de77-37b5-49c9-ad25-a8c0265f0997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-923']</value>
      <webElementGuid>2112e579-af17-460d-85c1-92c15eb956ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>d369ad72-ffa6-4008-8a5b-b5e212d0f9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fca5c5d9-9b11-4896-9b46-b920b0663ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-923' and @type = 'text']</value>
      <webElementGuid>b72cc416-c218-4604-8e2a-f2287fd1caaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
